// Project Euler: Problem 2: Even Fibonacci Numbers
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.

function fiboEvenSum(n) {

    let prev = 1;
    let current = 2;
    let sum = 0;

    let totalSum = 2;

    while(sum <= n){
        sum = current + prev;
        prev = current;
        current = sum;

        if(current %2 ===0){
            totalSum+=current;
        }
    }
    console.log('Final Val is : ' + totalSum)
  }
  
  fiboEvenSum(10);
  